### ISSUE TITLE
Questions about translation

### ISSUE THREAD

**Issue by shg166** [algernon-A/AlgernonCommons#1]
Hello.
Should I translate the languages in this shared framework?
Or if you are willing to deal with Crowdin translations, we will do nothing.
If translation is needed, we will fork it and PR it.

**Comment by algernon-A** [comment]
The translations are currently being doing on a per-mod basis, but I will soon be setting up a CrowdIn for the commons translations.  I'll let you know here when that's ready.

**Comment by shg166** [comment]
Thanks for the reply.
When the work becomes available on Crowdin, I will translate it there.
I will leave this Issues open.

**Comment by algernon-A** [comment]
The CrowdIn project is now available at https://crowdin.com/project/algernoncommons

**Comment by shg166** [comment]
Thank you again for your reply.
I will translate the content when it is added.
This Issue is closed.
