### ISSUE TITLE
Keybinding settings are not persisted?

### ISSUE THREAD

**Issue by ST-Apps** [algernon-A/AlgernonCommons#2]
Hi there, I'm trying to modernize Parallel Road Tool and I found out this great repo.
I've started rewriting stuff to use your code, but I'm having some issues with settings and keybindings.

Main issue is that I can change a keybinding, but the change will be lost as soon as I close the options panel and reopen it. It also doesn't correctly load the defaults that I'm setting.

Here are some implementation details:

```csharp
// OptionsPanel.ctor
var keyBindingsGroup = (UIHelper)helper.AddGroup(Translations.Translate("GROUP_KEYBINDINGS_NAME"));
((UIPanel)keyBindingsGroup.self).gameObject.AddComponent<ToggleButtonOptionsKeymapping>();

// ToggleButtonOptionsKeymapping
public class ToggleButtonOptionsKeymapping : OptionsKeymapping
{
    public ToggleButtonOptionsKeymapping()
    {
        Label = Translations.Translate("SELECT_KEYMAPPING_TOGGLEBUTTON_LABEL");
        ButtonLabel = Translations.Translate("PRESS_ANY_KEY");
    }

    protected override InputKey KeySetting
    {
        get => ModSettings.KeyPaste.Encode();
        set => ModSettings.KeyPaste.SetKey(value);
    }
}

// ModSettings
[XmlRoot("SettingsFile")]
public class ModSettings : SettingsXMLBase
{
    ...
    [XmlElement]
    public static readonly Keybinding KeyPaste = new(KeyCode.P, true, false, false);
    ...

    internal static void Load() => XMLFileUtils.Load<ModSettings>(SettingsFileName);
    internal static void Save() => XMLFileUtils.Save<ModSettings>(SettingsFileName);
}
```

What I'd expect to have in my `OptionsPanel` would be a pre-selected `CTRL+P` keybinding, however, if I remove the `ButtonLabel`, it shows as `ctrl+alt+shift+A` (which rings like a default value).

Also, I click and set a new value, the value is shown correctly just for it to be reverted as soon as I close the panel.

The XML file doesn't contain anything related to the keybinding, so I assume it's not saved correctly somehow.

Can you please help me with that?

**Comment by algernon-A** [comment]
Serializable XML elements can't be static; you need an instance property there instead (which in turn can reference your static field/property).

E.g.:
```
/// <summary>
/// Gets or sets the paste hotkey.
/// </summary>
[XmlElement("KeyPaste")]
public Keybinding XMLKeyPaste { get => ModSettings.KeyPaste ; set => ModSettings.KeyPaste = value; }
```

**Comment by ST-Apps** [comment]
It was a combination of two things, this one and the wrong way of setting text in te UI control. Thanks for the input!
